version: "3.3"

services:
  fitness-app-api:
    # network_mode: bridge
    image: fitness-app-api
    build: ./
    environment:
      # GUNICORN
      - FITNESS_APP_API_PYTHON_PORT=5000

      # LOGS
      - NIVEL_LOGS=INFO
      - DIRECTORIO_LOGS=logs/

      # APP
      - POOL_SIZE_DEFAULT=50
      - MAX_OVERFLOW_DEFAULT=100
      - DIRECTORY_FILES=files/
      - FITNESS_APP_API_ENVIRONMENT_MODE=development

    restart: always
    volumes:
      - ./logs:/usr/src/logs
      - ./files:/usr/src/files
      
    ports:
      - 5000:5000
